version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Burak115
      - DATABASE_NAME=tarznet
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=asdjf63463lkjFADSFA223Faalkfjaljasdf23236lkjafalaFADS
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Burak115
      - POSTGRES_DB=tarznet
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: